name: zibashu_android
repository: https://zibashu4.com

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    run: melos exec -- flutter analyze
  test:
    run: melos exec -- flutter test
  get:
    run: melos exec -- flutter pub get
