name: flux
description: Flux VPN — ziBashu-linked private network client (HULK foundation, locked).
publish_to: none
version: 0.3.0+3

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  zibashu_core:
    path: ../../packages/zibashu_core
  zibashu_ui:
    path: ../../packages/zibashu_ui
  zibashu_auth:
    path: ../../packages/zibashu_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/